import styles from '@/styles/help.module.css'
import Head from 'next/head'
import Navbar from '@/components/Navbar'
import Collapsible from '@/components/Collapsible'
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';
import { faDiscord } from '@fortawesome/free-brands-svg-icons'

export default function help() {
    return (
        <>
            <Head>
                <title>Continuity | Help</title>
                <meta name="description" content="Experience seamless and productive browsing with Continuity - tabs synced across all devices, secure personal info, a built-in content creator mind, and much more!" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Navbar downloadLink={"/#download"} />
            <main className={styles.main}>
                <div className={styles.heading}>Help</div>
                <div className={styles.subheading}>
                    Stuck on a question?
                </div>

                <a href="https://discord.gg/TwJ863WJsQ" rel="noreferrer" target="_blank">
                    <span className={styles.option}>
                        <FontAwesomeIcon icon={faDiscord} style={{ color: 'rgba(88, 101, 242, 1)', fontSize: 'large' }} />
                        <span style={{ fontSize: 'large', fontWeight: 'bold' }}>Join our Discord group</span>
                    </span>
                </a>

                <div className={styles.light_text}>
                    for speedy and personalized assistance! Plus, it is a great way to connect with other like-minded friends.
                </div>

                <div className={styles.subheading} style={{ marginTop: '4rem', marginBottom: '2rem' }}> Frequently Asked Questions</div>
                <Collapsible data={list} />
            </main>
        </>
    )
}


const renderRow = (heading: string, data: string) => {
    return (
        <li>
            <span style={{ fontWeight: 'bold', fontSize: 'large', marginRight: '0.5rem' }}>{heading}</span>: {data}
        </li>
    );
}


const list = [
    {
        title: "How can I access my webpages across all my devices with Continuity?",
        content: "Continuity makes it easy to access your webpages on all your devices at once. All you need to do is sign in to the Continuity app and chrome extension with the same google account on each device, and your tabs will automatically sync in real time. No hassle, no fuss. Try it out and see how convenient it can be!"
    },

    {
        title: "What are some key features of Continuity?",
        content: (
            <ul className={styles.feature_list}>
                {renderRow("Ultra Search", "Continuity not just smart but a creative browser! UltraSearch provides quick, precise, and personalized suggestions to your questions generated by AI, and custom tailored just for you, making it easier than ever to find what you're looking for.")}
                {renderRow("Intelligent Privacy Report", "Continuity offers in-depth tracking protection and reports on websites that may collect your personal information, providing a secure, private, and powerful browsing experience.")}
                {renderRow("Real-time tab synchronization", "Continuity allows you to access your tabs across all your devices in real-time, regardless of their operating system. Currently, Continuity works on Android, iPhones, and Windows devices, with plans to expand to other systems.")}
                {renderRow("A seamless user experience", "Continuity is designed to provide a smooth, productive, and efficient browsing experience.")}
            </ul>
        )
    }
]