import Head from 'next/head'
import { Inter } from '@next/font/google'
import Hero from '@/components/Hero'
import Features from '@/components/Features'
import Navbar from '@/components/Navbar'
import { useRef } from 'react'
import "animate.css/animate.min.css"
import Footer from '@/components/Footer'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  const scrollRef = useRef(null);
  return (
    <>
      <Head>
        <title>Continuity</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={inter.className}>
        <Navbar scrollTarget={scrollRef} />
        <Hero />
        <Features scrollTarget={scrollRef} />
        <Footer />
      </main>
    </>
  )
}
