version: '3.3'
services:
  nginx:
    build: ./nginx
    ports:
      - '80:80'
      - '443:443'
  mongo:
    image: mongo:4.2.5
    volumes:
      - mongo:/var/lib/docker/volumes/
  app:
    build: .
    volumes:
      - app:/var/lib/docker/volumes/
    environment:
      FLASK_APP: backend/server.py
      ADMIN_PASSWORD: '317E7FF22A1F3E7E64EC5CFE4CC555E2041CC9420176F64C8B7B133C9A1562AD'
      ADMIN_USERNAME: 'ADMIN_USER_1CF84C7B381F018E6ED5F2C6919EF8FC258EFCD82A1D4FC384B12FCEE81A9AFC'
      OPENAI_API_KEY: 'TEMP HOLDER'
      PUBLISHABLE_KEY: 'pk_test_51MZPKhAuOsRyx3wnNVUjI35JuPSJrDzO6KPhD25fOQ9u79WkIByXGtlbH8CQHWtEYHzMpnl5X4r02Gso4iE7FCSh00aOC1tJuK'
      SECRET_KEY: 'sk_test_51MZPKhAuOsRyx3wnA0pIs2m1l3sDeI00TdxjeZyb9RfHfdDYMB4dP2DJKtXKyvbbPMVftW9g7LsPmLUnEfTB6iVa00s4zV1WP1'
      WEBHOOK: ''
    # ports:
    #   - '80:8000'
volumes:
  mongo:
  app: