import { useContext } from "react";
import {
    ScrollView,
    Text,
    StyleSheet,
    SafeAreaView,
    StatusBar,
    View,
    Linking
} from "react-native";
import { StateContext } from "./state_context";


const PrivacyPolicy = () => {
    const { colorScheme } = useContext(StateContext);

    const styles = StyleSheet.create({
        root: {
            flex: 1,
            justifyContent: 'center',
            display: 'flex',
            backgroundColor: (colorScheme === 'dark') ? 'rgba(28, 28, 30, 1)' : 'rgba(242, 242, 247, 1)',
            padding: 10,
        },

        scrollContainer: {
            flex: 1,
            padding: 10,
        },

        text_style: {
            color: colorScheme === 'dark' ? 'rgba(209, 209, 214, 1)' : 'rgba(58, 58, 60, 1)',
            margin: 10,
        },

        heading: {
            textAlign: "center",
            fontWeight: 'bold',
            fontSize: 30,
            color: colorScheme === 'dark' ? '#fff' : '#000',
            padding: 10,
        },

        link: {
            color: 'rgba(10, 132, 255, 1)'
        }
    });

    return (
        <SafeAreaView style={styles.root}>
            <StatusBar animated={true}
                barStyle={colorScheme == 'dark' ? 'light-content' : 'dark-content'}
            />
            <ScrollView style={styles.scrollContainer}>
                <Text style={styles.heading}>Terms of Use</Text>
                <Text style={styles.text_style}>By using Ultra Search, you agree to the terms of use outlined in the OpenAI Terms of Service, which can be found at <Text style={styles.link} onPress={() => Linking.openURL('https://openai.com/terms/')}>https://openai.com/terms/</Text>. You also acknowledge and agree to the OpenAI Privacy Policy, which can be found at <Text style={styles.link} onPress={() => Linking.openURL('https://openai.com/privacy/')}>https://openai.com/privacy/</Text>. Please review these documents carefully before using Ultra Search.</Text>
                <Text style={styles.text_style}>If you have any questions or concerns about the OpenAI ChatGPT API, please contact OpenAI at <Text style={styles.link} onPress={() => Linking.openURL('mailto:support@openai.com')}>support@openai.com</Text> for more information.</Text>

                <Text style={styles.heading}>Disclaimer</Text>
                <Text style={styles.text_style}>Ultra Search is a feature of the Continuity app that utilizes the OpenAI ChatGPT API to provide quick, diverse, and precise suggestions to your questions. While we strive to provide accurate and helpful responses, please be aware that the responses generated by Ultra Search may sometimes be incorrect or inappropriate. We recommend using your own judgment and fact-checking any information provided by Ultra Search before making any decisions based on it.</Text>
                <View
                    style={{
                        borderBottomColor: '#a9a9a9',
                        borderBottomWidth: StyleSheet.hairlineWidth,
                        marginVertical: 20,
                    }}
                />

                <Text style={{ color: colorScheme === 'dark' ? 'rgba(142, 142, 147, 1)' : 'rgba(72, 72, 74, 1)', textAlign: "center" }}>Updated December 22, 2022</Text>
            </ScrollView>
        </SafeAreaView>
    );
};

export default PrivacyPolicy;